# Generated by Django 5.0.4 on 2024-04-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Netflix', '0003_alter_userprofile_managers_remove_movies_genre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='cast',
        ),
        migrations.RenameField(
            model_name='episodes',
            old_name='about',
            new_name='aboutEpisode',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='ratings',
            new_name='rating',
        ),
        migrations.RemoveField(
            model_name='tvshows',
            name='genre',
        ),
        migrations.AddField(
            model_name='movies',
            name='actors',
            field=models.ManyToManyField(to='Netflix.actors'),
        ),
        migrations.AddField(
            model_name='movies',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tvshows',
            name='actors',
            field=models.ManyToManyField(to='Netflix.actors'),
        ),
        migrations.AddField(
            model_name='tvshows',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tvshows',
            name='genres',
            field=models.ManyToManyField(to='Netflix.genre'),
        ),
        migrations.DeleteModel(
            name='Cast',
        ),
        migrations.DeleteModel(
            name='Description',
        ),
    ]
