# Generated by Django 5.0.4 on 2024-04-24 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Netflix', '0006_movies_release_date_tvshows_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='Netflix.subscriptionplan'),
        ),
    ]
