# Generated by Django 5.0.4 on 2024-04-24 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Netflix', '0007_alter_profile_subscription_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continuewatching',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Netflix.profile'),
        ),
        migrations.AlterField(
            model_name='mylist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Netflix.profile'),
        ),
    ]
