# Generated by Django 5.0.4 on 2024-04-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Netflix', '0008_alter_continuewatching_user_alter_mylist_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='continuewatching',
            old_name='movies',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='continuewatching',
            old_name='user',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='continuewatching',
            old_name='tvShows',
            new_name='tv_show',
        ),
        migrations.RenameField(
            model_name='mylist',
            old_name='movies',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='mylist',
            old_name='user',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='mylist',
            old_name='tvShows',
            new_name='tv_show',
        ),
        migrations.AddField(
            model_name='continuewatching',
            name='last_watched_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
