# Generated by Django 5.0.4 on 2024-04-29 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Netflix', '0010_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvshows',
            name='movietype',
        ),
    ]
