# Generated by Django 5.0.4 on 2024-04-29 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Netflix', '0011_remove_tvshows_movietype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mobile_no',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subscription_plan',
        ),
    ]
