# Generated by Django 5.0.4 on 2024-05-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Netflix', '0012_remove_profile_email_remove_profile_mobile_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvshows',
            name='video',
        ),
        migrations.AddField(
            model_name='episodes',
            name='thumbnailImage',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail'),
        ),
        migrations.AddField(
            model_name='episodes',
            name='video',
            field=models.ManyToManyField(to='Netflix.video'),
        ),
    ]
